### ISSUE TITLE
Using this libs technique with Google Tag Manager doesn't work in Firefox

### ISSUE THREAD

**Issue by ryanseddon** [olark/lightningjs#10]
So here's the deal using this library or the technique behind it inside google tag manager (gtm) that will handle the script injection doesn't load in Firefox... it's super weird and I can't quite narrow down why it's happening.

It correctly loads the snippet pasted in gtm, creates the non-blocking iframe but fails to attach the onload attribute to the body so nothing actually gets loaded from that point! All other browsers are fine.

If I copy and paste the injected snippet from gtm and comment out the gtm code that grabs the tag it works fine in firefox.

Has anyone else come across this?

**Comment by mjpizz** [comment]
hey Ryan! When using GTM, I think you will want to use a different loading technique thank LightningJS (which was built to work standalone). That said, if you find a workaround, happy to take a pull request :)

**Comment by ryanseddon** [comment]
Yep we ended up suggesting a different snippet since gtm is loaded async anyway.
