### ISSUE TITLE
How to load jQuery into my inner window?

### ISSUE THREAD

**Issue by atkinson** [olark/lightningjs#2]
Hey guys this is awesome.

If my third-party library depends on jquery, how would you recommend I safely load that into the same private window?

... or should I just paste it into the start of my lightening loaded lib?

thanks so much

**Comment by mjpizz** [comment]
Glad you like it!  We do have some progress on a backwards-compatibility layer that might be helpful in the future, but for now I would recommend pasting jQuery into the start of your lightning-loaded library :)

**Comment by bryanlarsen** [comment]
@mjpizz, any progress on this backwards-compatibility layer you promised?

**Comment by mjpizz** [comment]
hi Bryan, we ended up at a dead end on that backwards-compat layer unfortunately. Sorry about that!
