### ISSUE TITLE
set window.id causes exception

### ISSUE THREAD

**Issue by codebrew** [olark/lightningjs#3]
I've recently migrated a bookmarklet to using lightningjs and it works great except on one particular site.  http://www.freepeople.com/clothes-dresses-rompers-party-dresses/ballerina-princess-dress

When invoking my deferred call the following exception is thrown "cannot call deferred method 'init' on 'undefined' ". 

Ive traced it to when the site has set window.id to a non-zero value. The promiseFunctionId is getting set to this window.id value inside embed.js however this id value doesn't seem to be reflected when setting up a provide in the bootstrap.js.

I'm not sure if I'm just setting up something incorrectly or if its a bug with lightningjs.

**Comment by codebrew** [comment]
just to update this, I modified the test.html to set window.id = 1233245245; at the top of the inline javascript. This causes all the tests to fail.

**Comment by mjpizz** [comment]
I merged in the related pull request (aa718215ea6eada2e686160bcd9dd9e422253a67) so I think this is closed now
