### ISSUE TITLE
document.defaultView.getComputedStyle(node, null) is null

### ISSUE THREAD

**Issue by jjaffeux** [olark/lightningjs#5]
Hi,

using ligthning-js I have the following message with firefox, and nothing works  : document.defaultView.getComputedStyle(node, null) is null @ .../loader.js?lv=1:59

Everything is fine under chrome.

**Comment by mjpizz** [comment]
Hi there Joffrey, do you have any sample code I could use to reproduce the issue?  On my side, the benchmark works fine on all copies of Firefox that I have tried (version 2 and above).

**Comment by jjaffeux** [comment]
Hi it was caused by another script (jsscrollpane) who doesn't like to be in the lightning js iframe, tried different things with window.parent with no success.

I changed the library. Anyway thx for sharing ligthning js.

**Comment by mjpizz** [comment]
Thanks for the followup Joffrey.

**Comment by Lethea** [comment]
I've the same problem in using the Vimeo Embed Code . And I Open it in Colorbox , 
So here my problem
s.getComputedStyle(this, null) is null .
the vimeo code said that , I dont know where can I get place , I dont have a placeholder . So
I took the embed code in div which have a margin-top and width , by the way problem fixed
