### ISSUE TITLE
Already asynchronous calls?

### ISSUE THREAD

**Issue by ericelliott** [olark/lightningjs#7]
Hi,

I have some methods that are already asynchronous by nature. Is there any way for me to override the default behavior and control when the deferreds get resolved?

Otherwise, I'm going to have to break up the API and have people pass in callbacks, or return promises inside promises... that seems awkward!  =)

**Comment by mjpizz** [comment]
I think I see what you mean - do you have your own promise-style API?  If you could you throw together a quick example, that'd help to make sure I understand your use-case.

**Comment by ericelliott** [comment]
It's a little wonky to stack a promise-style API on top of a promise-style API, so I'm resorting to callbacks. Here's what I have right now:

```
tout('getSomeData', {
  callback: function (response) {
    // do stuff
  }
}).then(success, error);
```

I use this callback because I can't simply return synchronously from the function as lightningjs expects. 

See how that's awkward?

It would be really cool if I could just resolve the method's promise manually so users could count on the .then() callbacks to give them the asynchronous values.

**Comment by ericelliott** [comment]
Ideal use case:

```
myAPI('getSomeData', params).then(success, error);
```

And inside getSomeData:

```
// do some asynchronous stuff here
promise.resolve(data);
return promise;
```

Inside lightningjs, you could check to see if the return value is a promise, if so, replace the `myAPI` promise with the promise returned from `getSomeData`.

**Comment by mjpizz** [comment]
Got it, thanks Eric.  This makes sense to me, though I'm not sure of the "right" way to detect whether a return value is a promise.  Is there something similar to AMD's `if (define.amd)` convention?  Alternatively, you could add a decorator like `lightningjs.promise` that flags a `provide`ed method as returning its own promise.

If you want to throw together a pull request, this sounds like a pretty solid improvement.

**Comment by mjpizz** [comment]
Closing this out since it has been sitting for a while - @dilvie feel free to reopen with a PR if you ended up going this route
