### ISSUE TITLE
Ubertags and firefox

### ISSUE THREAD

**Issue by keepitterron** [olark/lightningjs#8]
A client is using our code via ubertags, works perfectly in all browsers with the exception of firefox, where the lightningjs iframe is completely empty.
Here's the link: http://www.shrm.org/HRAnswers/Pages/default.aspx you can see the feedback button on all browsers but firefox.

**Comment by mjpizz** [comment]
It's been a year on this, and I'm not sure that supporting ubertags is in the scope of LightningJS.  If you eventually did figure out a workaround, would be happy to take a pull request though.
