### ISSUE TITLE
Unable to make simple script loading to work. Is there some issue or am i missing something?

### ISSUE THREAD

**Issue by vikram-chaitanya** [olark/lightningjs#9]
Hi,

I am trying to use lightingjs and wanted to try a simple example. But i cant even make a simple javascript to load and execute. Here is the script i am trying: 

```
<html>
<head>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js"></script>
  <script type='text/javascript' src="./lightningjs-embed.min.js"> </script>
  <script type='text/javascript'> 
    window.piratelib = lightningjs.require("piratelib", "./sample.js");
    piratelib("testfun");
  </script>

</head>
<body>
  Hi...Hello, World!
</body>
</html>
```

The sample.js script has simple one line function: 

```
var testfun = function(){
  console.log('called testfun function');
};
```

Can you please let me know if there is some issue with the lightingjs or am i doing something wrong?

**Comment by science** [comment]
+1 - I was reading the README docs and couldn't figure out the same issue. Clarifying the total newb start up code would be appreciated!

**Comment by robinbb** [comment]
@vikramnet2003 it looks like you must begin the second argument of the `require` function with `//`. Starting with `./` will not work.

**Comment by mjpizz** [comment]
@vikramnet2003 I think you might just want to use "sample.js" instead of "./sample.js". If I recall correctly, we wrote lightingjs to expect a full URL there, so I'm not sure a relative path will work.

Are you running a local server? i.e. could you use something like "//localhost:3001/sample.js"?

**Comment by mjpizz** [comment]
I'm going to close this out - happy to help if you need anything else!
